name: Build and Sign Android APK

on:
  push:
    branches: [ trunk ]

jobs:
  build-android:
    runs-on: windows-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x  

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Verify MAUI workload Installation
        run: dotnet workload list

      - name: Restore NuGet packages
        run: dotnet restore Demo.csproj


      - name: Decode and store keystore file
        run: |
          $keystoreBytes = [System.Convert]::FromBase64String("${{ secrets.ANDROID_KEYSTORE_BASE64 }}")
          Set-Content -Path "qi-release-key.keystore" -Value $keystoreBytes -AsByteStream
        working-directory: ${{ github.workspace }}

      - name: Build Android Release
        run: dotnet publish -f net9.0-android Demo.csproj -c Release /p:AndroidKeyStore=true /p:AndroidSigningKeyStore=$env:GITHUB_WORKSPACE/qi-release-key.keystore /p:AndroidSigningKeyAlias="${{ secrets.ANDROID_KEYSTORE_ALIAS }}" /p:AndroidSigningKeyPass="${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" /p:EnableTrimmer=false

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: Signed-Android-APK
          path: Demo/bin/Release/net9.0-android/publish/*.apk
