name: Build and Sign Android APK

on:
  push:
    branches: [ trunk ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ca-certificates \
            curl \
            jq \
            libicu-dev \
            zlib1g \
            libssl-dev

      - name: Install .NET SDK from Script
        env:
          DOTNET_VERSION: 9.0.x
          DOTNET_INSTALL_DIR: /usr/local/share/dotnet
        run: |
          echo "Downloading .NET SDK $DOTNET_VERSION"
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel $DOTNET_VERSION --install-dir $DOTNET_INSTALL_DIR

          echo "Adding .NET SDK to PATH"
          echo "$DOTNET_INSTALL_DIR" >> $GITHUB_PATH

          echo "Verifying .NET SDK installation"
          dotnet --info

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Verify MAUI workload Installation
        run: dotnet workload list

      - name: Restore NuGet packages
        run: dotnet restore Demo.csproj

      - name: Decode and store keystore file
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > qi-release-key.keystore
        working-directory: ${{ github.workspace }}

      - name: Build Android Release
        run: dotnet publish Demo.csproj -c Release /p:AndroidKeyStore=true /p:AndroidSigningKeyStore=$GITHUB_WORKSPACE/qi-release-key.keystore /p:AndroidSigningKeyAlias=${{ secrets.ANDROID_KEY_ALIAS }} /p:AndroidSigningKeyPass=${{ secrets.ANDROID_KEY_PASSWORD }} /p:AndroidSigningStorePass=${{ secrets.ANDROID_STORE_PASSWORD }} /p:EnableTrimmer=false

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: Signed-Android-APK
          path: Demo/bin/Release/net9.0-android/publish/*.apk

